import { Link, router, useForm, usePage } from '@inertiajs/react';
import { Button } from '@/components/ui/button';
import { FormField } from '@/components/ui/form-field';
import type { ActivityItem, IdentitySummary, PayoutAccount, TenantApplication } from '@/types/identity';

interface WorkspaceProps {
    activity: ActivityItem[];
    identity: IdentitySummary;
    payoutAccount: PayoutAccount | null;
    tenant: TenantApplication | null;
}

export default function Workspace({ activity, identity, payoutAccount, tenant }: WorkspaceProps) {
    const page = usePage<{ flash?: { status?: string } }>();
    const profile = useForm({ name: identity.name, phone: identity.phone ?? '' });
    const payout = useForm({ bank_name: '', account_holder_name: '', account_number: '' });
    const closure = useForm({ reason: '' });
    const resubmission = useForm({
        business_name: tenant?.name ?? '',
        phone: tenant?.phone ?? '',
        outlet_name: tenant?.outletName ?? '',
        outlet_address: tenant?.outletAddress ?? '',
        city: tenant?.city ?? '',
        area: tenant?.area ?? '',
        latitude: tenant?.latitude?.toString() ?? '',
        longitude: tenant?.longitude?.toString() ?? '',
    });

    return <main className="min-h-screen bg-canvas px-4 py-6 text-ink sm:px-6 lg:px-10">
        <div className="mx-auto max-w-6xl">
            <header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-muted">Identity workspace</p><h1 className="mt-1 text-3xl font-black">Halo, {identity.name}</h1><p className="mt-1 text-sm text-muted">{identity.roleLabel} · {identity.status}</p></div><div className="flex flex-wrap gap-2"><Link href="/outlets" className="inline-flex min-h-11 items-center rounded-xl border border-line bg-white px-4 text-sm font-bold">Cari outlet</Link>{identity.role === 'customer' && <><Link href="/orders" className="inline-flex min-h-11 items-center rounded-xl bg-brand-950 px-4 text-sm font-bold text-white">Order saya</Link><Link href="/customer/addresses" className="inline-flex min-h-11 items-center rounded-xl border border-line bg-white px-4 text-sm font-bold">Alamat</Link></>}{identity.role === 'tenant_owner' && tenant?.onboardingStatus === 'approved' && <><Link href="/tenant/orders" className="inline-flex min-h-11 items-center rounded-xl border border-line bg-white px-4 text-sm font-bold">Order</Link><Link href="/tenant/operations" className="inline-flex min-h-11 items-center rounded-xl bg-brand-950 px-4 text-sm font-bold text-white">Operasional</Link></>}<Link href="/identity/security" className="inline-flex min-h-11 items-center rounded-xl border border-line bg-white px-4 text-sm font-bold">Security</Link>{identity.role === 'super_user' && <><Link href="/super-user/tenants" className="inline-flex min-h-11 items-center rounded-xl bg-brand-950 px-4 text-sm font-bold text-white">Tenant review</Link><Link href="/super-user/platform-settings" className="inline-flex min-h-11 items-center rounded-xl border border-line bg-white px-4 text-sm font-bold">Platform</Link></>}<Button variant="ghost" onClick={() => router.post('/logout')}>Keluar</Button></div></header>
            {(identity.role === 'tenant_owner' || identity.role === 'driver') && (
                <nav aria-label="Operasional Driver" className="mt-5 flex flex-wrap gap-2">
                    {identity.role === 'tenant_owner' && <>
                        <Link href="/tenant/drivers" className="inline-flex min-h-11 items-center rounded-xl border border-line bg-white px-4 text-sm font-bold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-700">Driver & komisi</Link>
                        <Link href="/tenant/dispatch" className="inline-flex min-h-11 items-center rounded-xl border border-line bg-white px-4 text-sm font-bold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-700">Dispatch pickup</Link>
                    </>}
                    {identity.role === 'driver' && <Link href="/driver/tasks" className="inline-flex min-h-11 items-center rounded-xl bg-brand-950 px-4 text-sm font-bold text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-700">Tugas Driver</Link>}
                </nav>
            )}
            {page.props.flash?.status && <p className="mt-5 rounded-xl bg-success-soft p-4 text-sm font-bold text-success">{page.props.flash.status}</p>}
            <div className="mt-6 grid gap-5 lg:grid-cols-2">
                <section className="rounded-panel border border-line bg-surface p-6 shadow-panel"><h2 className="text-lg font-black">Profil</h2><form className="mt-5 space-y-4" onSubmit={(e) => { e.preventDefault(); profile.patch('/identity/profile'); }}><FormField label="Nama" name="name" value={profile.data.name} error={profile.errors.name} onChange={(e) => profile.setData('name', e.target.value)} /><FormField label="Telepon" name="phone" value={profile.data.phone} error={profile.errors.phone} onChange={(e) => profile.setData('phone', e.target.value)} /><Button type="submit" disabled={profile.processing}>Simpan profil</Button></form></section>
                <section className="rounded-panel border border-line bg-surface p-6 shadow-panel"><h2 className="text-lg font-black">Status akses</h2><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-muted">Email</dt><dd className="font-bold">{identity.emailVerified ? 'Terverifikasi' : 'Belum'}</dd></div><div><dt className="text-muted">2FA</dt><dd className="font-bold">{identity.twoFactorEnabled ? 'Aktif' : 'Belum aktif'}</dd></div>{tenant && <><div><dt className="text-muted">Payout hold</dt><dd className="font-bold">{tenant.payoutHold ? 'Ditahan' : 'Tidak'}</dd></div><div><dt className="text-muted">Rekening payout</dt><dd className="font-bold">{payoutAccount?.verificationStatus ?? 'Belum diajukan'}</dd></div></>}</dl></section>
                {tenant && <section className="rounded-panel border border-line bg-surface p-6 shadow-panel lg:col-span-2"><h2 className="text-lg font-black">{tenant.name}</h2><p className="mt-2 text-sm text-muted">Onboarding: {tenant.onboardingStatus} · Operasional: {tenant.operationalStatus}</p>{tenant.reviewReason && <p className="mt-3 rounded-xl bg-warning-soft p-3 text-sm text-warning">{tenant.reviewReason}</p>}<p className="mt-3 text-sm text-copy">Outlet awal: {tenant.outletName}, {tenant.area}, {tenant.city}</p></section>}
                {tenant?.onboardingStatus === 'rejected' && <section className="rounded-panel border border-line bg-surface p-6 shadow-panel lg:col-span-2"><h2 className="text-lg font-black">Ajukan ulang pendaftaran</h2><p className="mt-1 text-sm text-muted">Perbarui data yang ditolak sebelum mengirim ulang.</p><form className="mt-5 grid gap-4 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); resubmission.post('/tenant/application/resubmission'); }}><FormField label="Nama bisnis" name="business_name" value={resubmission.data.business_name} error={resubmission.errors.business_name} onChange={(event) => resubmission.setData('business_name', event.target.value)} /><FormField label="Telepon" name="resubmission_phone" value={resubmission.data.phone} error={resubmission.errors.phone} onChange={(event) => resubmission.setData('phone', event.target.value)} /><FormField label="Nama outlet awal" name="outlet_name" value={resubmission.data.outlet_name} error={resubmission.errors.outlet_name} onChange={(event) => resubmission.setData('outlet_name', event.target.value)} /><FormField label="Alamat outlet" name="outlet_address" value={resubmission.data.outlet_address} error={resubmission.errors.outlet_address} onChange={(event) => resubmission.setData('outlet_address', event.target.value)} /><FormField label="Kota" name="city" value={resubmission.data.city} error={resubmission.errors.city} onChange={(event) => resubmission.setData('city', event.target.value)} /><FormField label="Area" name="area" value={resubmission.data.area} error={resubmission.errors.area} onChange={(event) => resubmission.setData('area', event.target.value)} /><FormField label="Latitude" name="latitude" type="number" step="any" value={resubmission.data.latitude} error={resubmission.errors.latitude} onChange={(event) => resubmission.setData('latitude', event.target.value)} /><FormField label="Longitude" name="longitude" type="number" step="any" value={resubmission.data.longitude} error={resubmission.errors.longitude} onChange={(event) => resubmission.setData('longitude', event.target.value)} /><Button className="sm:col-span-2 sm:justify-self-start" type="submit" disabled={resubmission.processing}>Ajukan ulang</Button></form></section>}
                {tenant?.onboardingStatus === 'approved' && tenant.operationalStatus === 'active' && <section className="rounded-panel border border-line bg-surface p-6 shadow-panel"><h2 className="text-lg font-black">Rekening payout</h2>{payoutAccount && <p className="mt-3 rounded-xl bg-canvas p-3 text-sm">{payoutAccount.bankName} · {payoutAccount.maskedHolderName} · {payoutAccount.maskedAccountNumber} · {payoutAccount.verificationStatus}</p>}<p className="mt-3 text-xs text-muted">Konfirmasi password dan TOTP berlaku 15 menit sebelum perubahan rekening.</p><Link href="/identity/confirm-sensitive-action" className="mt-3 inline-block text-sm font-bold text-brand-700">Konfirmasi tindakan sensitif</Link><form className="mt-4 space-y-3" onSubmit={(e) => { e.preventDefault(); payout.put('/tenant/payout-account'); }}><FormField label="Bank" name="bank_name" value={payout.data.bank_name} error={payout.errors.bank_name} onChange={(e) => payout.setData('bank_name', e.target.value)} /><FormField label="Nama pemilik" name="account_holder_name" value={payout.data.account_holder_name} error={payout.errors.account_holder_name} onChange={(e) => payout.setData('account_holder_name', e.target.value)} /><FormField label="Nomor rekening" name="account_number" inputMode="numeric" value={payout.data.account_number} error={payout.errors.account_number} onChange={(e) => payout.setData('account_number', e.target.value)} /><Button type="submit" disabled={payout.processing}>Kirim untuk verifikasi</Button></form></section>}
                {tenant && !tenant.closureRequested && tenant.onboardingStatus === 'approved' && <section className="rounded-panel border border-line bg-surface p-6 shadow-panel"><h2 className="text-lg font-black">Penutupan Tenant</h2><form className="mt-4 space-y-3" onSubmit={(e) => { e.preventDefault(); closure.post('/tenant/closure-requests'); }}><FormField label="Alasan" name="reason" value={closure.data.reason} error={closure.errors.reason} onChange={(e) => closure.setData('reason', e.target.value)} /><Button variant="secondary" type="submit">Ajukan penutupan</Button></form></section>}
                {activity.length > 0 && <section className="rounded-panel border border-line bg-surface p-6 shadow-panel lg:col-span-2"><h2 className="text-lg font-black">Audit terbaru</h2><ul className="mt-4 divide-y divide-line">{activity.map((item) => <li key={`${item.action}-${item.createdAt}`} className="py-3 text-sm"><span className="font-bold">{item.action}</span><span className="ml-2 text-muted">{new Date(item.createdAt).toLocaleString('id-ID')}</span></li>)}</ul></section>}
            </div>
        </div>
    </main>;
}
