import { Head, Link, router, useForm, usePage } from '@inertiajs/react';
import { ArrowLeft, Download } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { ConfirmButton } from '@/components/ui/confirm-button';
import { FormField } from '@/components/ui/form-field';
import { InteractiveBarChart } from '@/components/ui/interactive-bar-chart';
import { SelectField } from '@/components/ui/select-field';
import { StatusBadge } from '@/components/ui/status-badge';
import { TextareaField } from '@/components/ui/textarea-field';
import { financeMetricDescription, financeMetricLabel, payoutStatusLabels, refundStatusLabels } from '@/lib/finance-labels';
import type { RefundRequest, SupportFinancePage, TenantPayout } from '@/types/finance';

const money = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 });

function RefundCard({ refund }: { refund: RefundRequest }) {
    const review = useForm({ decision: 'approved', reason: '' });
    const complete = useForm({ method: 'bank_transfer', reference: '', reason: '' });
    return <Card className="p-5">
        <div className="flex justify-between gap-3"><div><Link href={`/finance/refunds/${refund.publicId}`} className="font-black text-brand-700">{refund.orderNumber}</Link><p className="mt-1 text-sm text-muted">{money.format(refund.amount)}</p></div><StatusBadge tone={refund.status === 'completed' ? 'green' : refund.status === 'rejected' ? 'neutral' : 'amber'}>{refundStatusLabels[refund.status]}</StatusBadge></div>
        {refund.status === 'submitted' && <form className="mt-4 space-y-3" onSubmit={(event) => event.preventDefault()}><SelectField label="Keputusan" value={review.data.decision} onChange={(event) => review.setData('decision', event.target.value)}><option value="approved">Setujui</option><option value="rejected">Tolak</option></SelectField><TextareaField label="Alasan peninjauan" value={review.data.reason} error={review.errors.reason} onChange={(event) => review.setData('reason', event.target.value)} /><ConfirmButton title="Simpan keputusan pengembalian dana?" description={`Keputusan ${review.data.decision === 'approved' ? 'menyetujui' : 'menolak'} permintaan akan dicatat permanen.`} confirmLabel="Simpan keputusan" onConfirm={() => review.post(`/super-user/refunds/${refund.publicId}/review`)} loading={review.processing} disabled={review.processing}>Simpan keputusan</ConfirmButton></form>}
        {refund.status === 'approved' && <form className="mt-4 space-y-3" onSubmit={(event) => event.preventDefault()}><FormField label="Referensi transfer" value={complete.data.reference} error={complete.errors.reference} onChange={(event) => complete.setData('reference', event.target.value)} /><TextareaField label="Alasan penyelesaian" value={complete.data.reason} error={complete.errors.reason} onChange={(event) => complete.setData('reason', event.target.value)} /><ConfirmButton title="Tandai pengembalian dana selesai?" description="Pastikan transfer sudah dilakukan; status selesai tidak dapat dibatalkan." confirmLabel="Tandai selesai" onConfirm={() => complete.post(`/super-user/refunds/${refund.publicId}/completion`)} loading={complete.processing} disabled={complete.processing}>Tandai selesai</ConfirmButton></form>}
    </Card>;
}

function TenantPayoutCard({ payout }: { payout: TenantPayout }) {
    const finalize = useForm({ method: 'bank_transfer', reference: '', reason: '' });
    const voidForm = useForm({ reason: '' });
    return <Card className="p-5">
        <div className="flex justify-between gap-3"><div><Link href={`/finance/tenant-payouts/${payout.publicId}`} className="font-black text-brand-700">{payout.batchReference}</Link><p className="mt-1 text-sm text-muted">Bersih {money.format(payout.netAmount)} · {payout.bankName} {payout.maskedAccountNumber}</p></div><StatusBadge tone={payout.status === 'finalized' ? 'green' : payout.status === 'pending_transfer' ? 'amber' : 'neutral'}>{payoutStatusLabels[payout.status]}</StatusBadge></div>
        {payout.status === 'pending_transfer' && <div className="mt-4 grid gap-4 md:grid-cols-2"><form className="space-y-3" onSubmit={(event) => event.preventDefault()}><FormField label="Referensi transfer" value={finalize.data.reference} error={finalize.errors.reference} onChange={(event) => finalize.setData('reference', event.target.value)} /><TextareaField label="Alasan finalisasi" value={finalize.data.reason} error={finalize.errors.reason} onChange={(event) => finalize.setData('reason', event.target.value)} /><ConfirmButton title="Finalisasi pencairan Tenant?" description="Pencairan akan menjadi final setelah transfer tercatat." confirmLabel="Finalisasi" onConfirm={() => finalize.post(`/super-user/tenant-payouts/${payout.publicId}/finalization`)} loading={finalize.processing} disabled={finalize.processing}>Finalisasi</ConfirmButton></form><form className="space-y-3" onSubmit={(event) => event.preventDefault()}><TextareaField label="Alasan pembatalan" value={voidForm.data.reason} error={voidForm.errors.reason} onChange={(event) => voidForm.setData('reason', event.target.value)} /><ConfirmButton title="Batalkan pencairan Tenant?" description="Pencairan dibatalkan dan sumber dana perlu direkonsiliasi ulang." confirmLabel="Batalkan pencairan" onConfirm={() => voidForm.post(`/super-user/tenant-payouts/${payout.publicId}/void`)} variant="secondary" loading={voidForm.processing} disabled={voidForm.processing}>Batalkan pencairan</ConfirmButton></form></div>}
    </Card>;
}

export default function SupportFinance({ metrics, refunds, tenantPayouts, tenants, filters }: SupportFinancePage) {
    const { flash } = usePage<{ flash?: { status?: string } }>().props;
    const [from, setFrom] = useState(filters.from); const [to, setTo] = useState(filters.to);
    const create = useForm({ tenant_public_id: tenants[0]?.publicId ?? '', cutoff: filters.to });
    const amountMetrics = Object.entries(metrics).filter(([label]) => label.toLowerCase().includes('amount') || label === 'grossPaid');
    const countMetrics = Object.entries(metrics).filter(([label]) => !label.toLowerCase().includes('amount') && label !== 'grossPaid');
    return <main className="min-h-screen bg-canvas px-4 py-6 text-ink sm:px-6"><Head title="Keuangan platform" /><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><Link href="/workspace" className="inline-flex items-center gap-2 text-sm font-bold text-brand-700"><ArrowLeft className="size-4" />Workspace</Link><h1 className="mt-2 text-3xl font-black">Keuangan & Rekonsiliasi</h1><p className="mt-2 text-sm text-muted">Pantau transaksi, pencairan, dan selisih melalui alur resmi.</p></div><a href={`/super-user/finance/export?from=${from}&to=${to}`} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-brand-600 px-4 text-sm font-bold text-white"><Download className="size-4" />Unduh CSV</a></header>{flash?.status && <p className="mt-5 rounded-xl bg-success-soft p-4 text-sm font-bold text-success">{flash.status}</p>}<form className="mt-6 grid gap-3 rounded-panel border border-line bg-surface p-5 sm:grid-cols-3" onSubmit={(event) => { event.preventDefault(); router.get('/super-user/finance', { from, to }, { preserveState: true, replace: true, only: ['metrics', 'filters'] }); }}><FormField label="Dari" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /><FormField label="Sampai" type="date" value={to} onChange={(event) => setTo(event.target.value)} /><Button className="self-end" type="submit">Terapkan</Button></form><section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(metrics).map(([key, value]) => <Card key={key} className="p-5" title={financeMetricDescription(key)}><p className="break-words text-xs font-bold uppercase text-muted">{financeMetricLabel(key)}<span className="sr-only">. {financeMetricDescription(key)}</span></p><p className="mt-2 text-2xl font-black">{key.toLowerCase().includes('amount') || key === 'grossPaid' ? money.format(value) : value}</p></Card>)}</section>
        <div className="mt-5 grid gap-5 xl:grid-cols-2"><InteractiveBarChart title="Nominal Keuangan" data={amountMetrics.map(([key, value]) => ({ label: financeMetricLabel(key), value }))} formatValue={(value) => money.format(value)} /><InteractiveBarChart title="Antrean & Selisih" data={countMetrics.map(([key, value]) => ({ label: financeMetricLabel(key), value }))} /></div>
        <div className="mt-8 grid gap-7 xl:grid-cols-2"><section><h2 className="text-xl font-black">Antrean pengembalian dana</h2><p className="mt-2 text-sm text-muted">Perlu konfirmasi password dan TOTP.</p><div className="mt-3 space-y-3">{refunds.items.map((refund) => <RefundCard key={refund.publicId} refund={refund} />)}</div></section><section><h2 className="text-xl font-black">Buat pencairan Tenant</h2><form className="mt-3 space-y-3 rounded-panel border border-line bg-surface p-5" onSubmit={(event) => event.preventDefault()}><SelectField label="Tenant" value={create.data.tenant_public_id} error={create.errors.tenant_public_id} onChange={(event) => create.setData('tenant_public_id', event.target.value)}><option value="">Pilih Tenant</option>{tenants.map((tenant) => <option key={tenant.publicId} value={tenant.publicId}>{tenant.name}</option>)}</SelectField><FormField label="Tanggal batas" type="date" value={create.data.cutoff} error={create.errors.cutoff} onChange={(event) => create.setData('cutoff', event.target.value)} /><ConfirmButton title="Buat pencairan Tenant?" description="Sistem memilih pembayaran yang memenuhi syarat hingga tanggal batas." confirmLabel="Buat pencairan" onConfirm={() => create.post('/super-user/tenant-payouts')} loading={create.processing} disabled={create.processing}>Buat pencairan</ConfirmButton></form><div className="mt-4 space-y-3">{tenantPayouts.map((payout) => <TenantPayoutCard key={payout.publicId} payout={payout} />)}</div></section></div><p className="mt-8 text-xs text-muted">Aksi sensitif memerlukan <Link href="/identity/confirm-sensitive-action" className="font-bold text-brand-700">konfirmasi password dan TOTP</Link>.</p></div></main>;
}
