import { Head, Link, router, useForm, usePage } from '@inertiajs/react';
import { ArrowLeft, Download } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { FormField } from '@/components/ui/form-field';
import { SelectField } from '@/components/ui/select-field';
import { StatusBadge } from '@/components/ui/status-badge';
import { TextareaField } from '@/components/ui/textarea-field';
import type { RefundRequest, SupportFinancePage, TenantPayout } from '@/types/finance';

const money = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 });

function RefundCard({ refund }: { refund: RefundRequest }) {
    const review = useForm({ decision: 'approved', reason: '' });
    const complete = useForm({ method: 'bank_transfer', reference: '', reason: '' });
    return <Card className="p-5"><div className="flex justify-between gap-3"><div><Link href={`/finance/refunds/${refund.publicId}`} className="font-black text-brand-700">{refund.orderNumber}</Link><p className="text-sm text-muted">{money.format(refund.amount)}</p></div><StatusBadge tone={refund.status === 'completed' ? 'green' : refund.status === 'rejected' ? 'neutral' : 'amber'}>{refund.status}</StatusBadge></div>{refund.status === 'submitted' && <form className="mt-4 space-y-3" onSubmit={(event) => { event.preventDefault(); review.post(`/super-user/refunds/${refund.publicId}/review`); }}><SelectField label="Keputusan" value={review.data.decision} onChange={(event) => review.setData('decision', event.target.value)}><option value="approved">Setujui</option><option value="rejected">Tolak</option></SelectField><TextareaField label="Alasan review" value={review.data.reason} error={review.errors.reason} onChange={(event) => review.setData('reason', event.target.value)} /><Button type="submit" disabled={review.processing}>Simpan review</Button></form>}{refund.status === 'approved' && <form className="mt-4 space-y-3" onSubmit={(event) => { event.preventDefault(); complete.post(`/super-user/refunds/${refund.publicId}/completion`); }}><FormField label="Referensi transfer" value={complete.data.reference} error={complete.errors.reference} onChange={(event) => complete.setData('reference', event.target.value)} /><TextareaField label="Alasan completion" value={complete.data.reason} error={complete.errors.reason} onChange={(event) => complete.setData('reason', event.target.value)} /><Button type="submit" disabled={complete.processing}>Tandai selesai</Button></form>}</Card>;
}

function TenantPayoutCard({ payout }: { payout: TenantPayout }) {
    const finalize = useForm({ method: 'bank_transfer', reference: '', reason: '' });
    const voidForm = useForm({ reason: '' });
    return <Card className="p-5"><div className="flex justify-between gap-3"><div><Link href={`/finance/tenant-payouts/${payout.publicId}`} className="font-black text-brand-700">{payout.batchReference}</Link><p className="text-sm text-muted">Net {money.format(payout.netAmount)} · {payout.bankName} {payout.maskedAccountNumber}</p></div><StatusBadge tone={payout.status === 'finalized' ? 'green' : payout.status === 'pending_transfer' ? 'amber' : 'neutral'}>{payout.status}</StatusBadge></div>{payout.status === 'pending_transfer' && <div className="mt-4 grid gap-4 md:grid-cols-2"><form className="space-y-3" onSubmit={(event) => { event.preventDefault(); finalize.post(`/super-user/tenant-payouts/${payout.publicId}/finalization`); }}><FormField label="Referensi transfer" value={finalize.data.reference} error={finalize.errors.reference} onChange={(event) => finalize.setData('reference', event.target.value)} /><TextareaField label="Alasan finalisasi" value={finalize.data.reason} error={finalize.errors.reason} onChange={(event) => finalize.setData('reason', event.target.value)} /><Button type="submit" disabled={finalize.processing}>Finalisasi</Button></form><form className="space-y-3" onSubmit={(event) => { event.preventDefault(); voidForm.post(`/super-user/tenant-payouts/${payout.publicId}/void`); }}><TextareaField label="Alasan void" value={voidForm.data.reason} error={voidForm.errors.reason} onChange={(event) => voidForm.setData('reason', event.target.value)} /><Button variant="secondary" type="submit" disabled={voidForm.processing}>Void batch</Button></form></div>}</Card>;
}

export default function SupportFinance({ metrics, refunds, tenantPayouts, tenants, filters }: SupportFinancePage) {
    const { flash } = usePage<{ flash?: { status?: string } }>().props;
    const [from, setFrom] = useState(filters.from); const [to, setTo] = useState(filters.to);
    const create = useForm({ tenant_public_id: tenants[0]?.publicId ?? '', cutoff: filters.to });
    return <main className="min-h-screen bg-canvas px-4 py-6 text-ink sm:px-6"><Head title="Finance platform" /><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><Link href="/workspace" className="inline-flex items-center gap-2 text-sm font-bold text-brand-700"><ArrowLeft className="size-4" />Workspace</Link><h1 className="mt-2 text-3xl font-black">Finance & rekonsiliasi</h1><p className="text-sm text-muted">Dashboard bersifat traceable; tidak menyediakan generic override.</p></div><a href={`/super-user/finance/export?from=${from}&to=${to}`} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-brand-950 px-4 text-sm font-bold text-white"><Download className="size-4" />Masked CSV</a></header>{flash?.status && <p className="mt-5 rounded-xl bg-success-soft p-4 text-sm font-bold text-success">{flash.status}</p>}<form className="mt-6 grid gap-3 rounded-panel border border-line bg-surface p-5 sm:grid-cols-3" onSubmit={(event) => { event.preventDefault(); router.get('/super-user/finance', { from, to }, { preserveState: true, replace: true, only: ['metrics', 'filters'] }); }}><FormField label="Dari" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /><FormField label="Sampai" type="date" value={to} onChange={(event) => setTo(event.target.value)} /><Button className="self-end" type="submit">Terapkan</Button></form><section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(metrics).map(([label, value]) => <Card key={label} className="p-5"><p className="break-words text-xs font-bold uppercase text-muted">{label}</p><p className="mt-2 text-2xl font-black">{label.toLowerCase().includes('amount') || label === 'grossPaid' ? money.format(value) : value}</p></Card>)}</section>
        <div className="mt-8 grid gap-7 xl:grid-cols-2"><section><h2 className="text-xl font-black">Refund queue</h2><p className="text-sm text-muted">Review memerlukan sensitive authentication aktif.</p><div className="mt-3 space-y-3">{refunds.items.map((refund) => <RefundCard key={refund.publicId} refund={refund} />)}</div></section><section><h2 className="text-xl font-black">Buat payout Tenant</h2><form className="mt-3 space-y-3 rounded-panel border border-line bg-surface p-5" onSubmit={(event) => { event.preventDefault(); create.post('/super-user/tenant-payouts'); }}><SelectField label="Tenant" value={create.data.tenant_public_id} error={create.errors.tenant_public_id} onChange={(event) => create.setData('tenant_public_id', event.target.value)}><option value="">Pilih Tenant</option>{tenants.map((tenant) => <option key={tenant.publicId} value={tenant.publicId}>{tenant.name}</option>)}</SelectField><FormField label="Cutoff" type="date" value={create.data.cutoff} error={create.errors.cutoff} onChange={(event) => create.setData('cutoff', event.target.value)} /><Button type="submit" disabled={create.processing}>Pilih semua source eligible</Button></form><div className="mt-4 space-y-3">{tenantPayouts.map((payout) => <TenantPayoutCard key={payout.publicId} payout={payout} />)}</div></section></div><p className="mt-8 text-xs text-muted">Finalisasi, void, dan review refund memerlukan <Link href="/identity/confirm-sensitive-action" className="font-bold text-brand-700">konfirmasi password + TOTP</Link>.</p></div></main>;
}
