import { Head, Link, useForm, usePage } from '@inertiajs/react';
import { ArrowLeft, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { FormField } from '@/components/ui/form-field';
import { TextareaField } from '@/components/ui/textarea-field';

interface Props { maxServiceRadiusKm: number; paymentMaintenanceEnabled: boolean; version: number; updatedAt: string | null }

export default function PlatformSettings({ maxServiceRadiusKm, version, updatedAt }: Props) {
    const { flash } = usePage<{ flash?: { status?: string } }>().props;
    const form = useForm({ maximum_service_radius_km: maxServiceRadiusKm.toString(), reason: '' });
    return <main className="min-h-screen bg-canvas px-4 py-6 text-ink sm:px-6"><Head title="Pengaturan platform" /><div className="mx-auto max-w-3xl"><Link href="/super-user/tenants" className="inline-flex items-center gap-2 text-sm font-bold text-brand-700"><ArrowLeft className="size-4" />Tenant review</Link><header className="mt-4"><p className="text-xs font-bold uppercase tracking-wider text-brand-600">Super User</p><h1 className="mt-2 text-3xl font-black">Pengaturan radius platform</h1><p className="mt-2 text-sm text-muted">Batas baru tidak dapat lebih kecil dari radius outlet yang masih terkonfigurasi.</p></header>{flash?.status && <p className="mt-5 rounded-xl bg-success-soft p-4 text-sm font-bold text-success">{flash.status}</p>}<section className="mt-6 rounded-panel border border-line bg-surface p-6 shadow-panel"><div className="flex items-center gap-3 rounded-xl bg-brand-50 p-4"><ShieldCheck className="size-6 text-brand-700" /><div><p className="text-sm font-black">Konfirmasi sensitif wajib</p><p className="text-xs text-muted">Password + TOTP berlaku 15 menit.</p></div></div><form className="mt-6 space-y-4" onSubmit={(event) => { event.preventDefault(); form.patch('/super-user/platform-settings/service-radius'); }}><FormField label="Radius maksimum (km)" type="number" min="1" max="100" value={form.data.maximum_service_radius_km} error={form.errors.maximum_service_radius_km} onChange={(event) => form.setData('maximum_service_radius_km', event.target.value)} /><TextareaField label="Alasan perubahan" value={form.data.reason} error={form.errors.reason} onChange={(event) => form.setData('reason', event.target.value)} /><div className="flex flex-wrap items-center gap-3"><Button type="submit" disabled={form.processing}>Simpan batas radius</Button><Link href="/identity/confirm-sensitive-action" className="text-sm font-bold text-brand-700">Konfirmasi tindakan sensitif</Link></div></form><p className="mt-6 border-t border-line pt-4 text-xs text-muted">Versi {version}{updatedAt ? ` · diperbarui ${new Date(updatedAt).toLocaleString('id-ID')}` : ''}</p></section></div></main>;
}
