import { Head, Link, router, usePage } from '@inertiajs/react';
import { ArrowLeft, CalendarDays, MapPin, Phone } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { SelectField } from '@/components/ui/select-field';
import type { AddressCoverage, AvailableSlot, CustomerAddress, OutletDetail } from '@/types/operations';

interface Props { outlet: OutletDetail; availableSlots: AvailableSlot[]; savedAddresses: CustomerAddress[]; coverage: AddressCoverage }
const money = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 });
const date = new Intl.DateTimeFormat('id-ID', { weekday: 'short', day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' });

export default function OutletShow({ outlet, availableSlots, savedAddresses, coverage }: Props) {
    const { auth } = usePage<{ auth: { user: { role: string } | null } }>().props;
    const [pickup, setPickup] = useState('');
    const [delivery, setDelivery] = useState('');
    const check = () => router.get(`/outlets/${outlet.publicId}`, { pickup_address: pickup, delivery_address: delivery }, { preserveState: true, preserveScroll: true, only: ['coverage'] });

    return <main className="min-h-screen bg-canvas text-ink"><Head title={outlet.name} /><div className="mx-auto max-w-6xl px-4 py-6 sm:px-6"><Link href="/outlets" className="inline-flex items-center gap-2 text-sm font-bold text-brand-700"><ArrowLeft className="size-4" />Kembali ke discovery</Link><div className="mt-6 grid gap-6 lg:grid-cols-[1.4fr_.6fr]"><section className="rounded-panel border border-line bg-surface p-6 shadow-panel"><p className="text-xs font-bold uppercase tracking-wider text-brand-600">{outlet.tenantName}</p><h1 className="mt-2 text-3xl font-black">{outlet.name}</h1><p className="mt-4 flex gap-2 text-sm text-muted"><MapPin className="size-4" />{outlet.address}, {outlet.area}, {outlet.city}</p><a href={`https://wa.me/${outlet.contactPhone.replace(/\D/g, '').replace(/^0/, '62')}`} className="mt-3 inline-flex items-center gap-2 text-sm font-bold text-brand-700"><Phone className="size-4" />{outlet.contactPhone}</a><dl className="mt-6 grid grid-cols-2 gap-4 rounded-xl bg-canvas p-4 text-sm"><div><dt className="text-muted">Radius</dt><dd className="font-black">{outlet.serviceRadiusKm} km</dd></div><div><dt className="text-muted">Biaya antar-jemput</dt><dd className="font-black">{money.format(outlet.pickupFee + outlet.deliveryFee)}</dd></div></dl><h2 className="mt-7 text-xl font-black">Paket aktif</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{outlet.packages.map((pkg) => <article key={pkg.publicId} className="rounded-xl border border-line p-4"><h3 className="font-black">{pkg.name}</h3><p className="mt-1 text-lg font-black text-brand-700">{money.format(pkg.unitPrice)}{pkg.pricingType === 'per_kg' ? '/kg' : '/unit'}</p><p className="mt-2 text-xs text-muted">Estimasi {pkg.estimatedDurationMinutes} menit · minimum {pkg.pricingType === 'per_kg' ? `${pkg.minimumWeightGrams} gram` : `${pkg.minimumQuantity} unit`}</p></article>)}</div><h2 className="mt-7 flex items-center gap-2 text-xl font-black"><CalendarDays className="size-5" />Jadwal 7 hari</h2><div className="mt-4 grid gap-2 sm:grid-cols-2">{availableSlots.slice(0, 12).map((slot) => <div key={`${slot.slotPublicId}-${slot.startsAt}`} className="rounded-xl bg-brand-50 p-3 text-sm"><span className="font-black capitalize">{slot.type}</span><span className="ml-2 text-muted">{date.format(new Date(slot.startsAt))}</span></div>)}</div></section>
            <aside className="space-y-5"><section className="rounded-panel border border-line bg-surface p-5 shadow-panel"><h2 className="text-lg font-black">Cek cakupan alamat</h2>{auth.user?.role !== 'customer' ? <p className="mt-3 text-sm text-muted"><Link href="/login" className="font-bold text-brand-700">Masuk sebagai Customer</Link> untuk memakai alamat tersimpan.</p> : savedAddresses.length === 0 ? <p className="mt-3 text-sm text-muted">Simpan alamat terlebih dahulu di <Link href="/customer/addresses" className="font-bold text-brand-700">Address book</Link>.</p> : <div className="mt-4 space-y-4"><SelectField label="Alamat pickup" value={pickup} onChange={(event) => setPickup(event.target.value)}><option value="">Pilih alamat</option>{savedAddresses.map((item) => <option key={item.publicId} value={item.publicId}>{item.label} — {item.area}</option>)}</SelectField><SelectField label="Alamat delivery" value={delivery} onChange={(event) => setDelivery(event.target.value)}><option value="">Pilih alamat</option>{savedAddresses.map((item) => <option key={item.publicId} value={item.publicId}>{item.label} — {item.area}</option>)}</SelectField><Button className="w-full" disabled={!pickup || !delivery} onClick={check}>Periksa radius</Button></div>}{coverage.pickup && <div className={`mt-4 rounded-xl p-3 text-sm font-bold ${coverage.ready ? 'bg-success-soft text-success' : 'bg-warning-soft text-warning'}`}>{coverage.ready ? 'Kedua alamat berada dalam radius.' : 'Salah satu alamat berada di luar radius.'}<p className="mt-1 text-xs font-medium">Pickup {coverage.pickup.distanceKm} km · Delivery {coverage.delivery?.distanceKm ?? '-'} km</p></div>}</section><section className="rounded-panel border border-line bg-surface p-5"><h2 className="font-black">Belum checkout</h2><p className="mt-2 text-sm text-muted">Milestone 3 hanya memvalidasi discovery, alamat, dan jadwal. Pembuatan order hadir pada Milestone 4.</p></section></aside></div></div></main>;
}
