import { Head, Link, router, useForm, usePage } from '@inertiajs/react';
import { ArrowLeft, MapPin, Star, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { EmptyState } from '@/components/ui/empty-state';
import { FormField } from '@/components/ui/form-field';
import { Pagination } from '@/components/ui/pagination';
import { TextareaField } from '@/components/ui/textarea-field';
import type { CustomerAddress, Paginated } from '@/types/operations';

interface AddressFormData { label: string; contact_name: string; contact_phone: string; address: string; city: string; area: string; latitude: string; longitude: string; location_consent: boolean; make_default: boolean }
const blank: AddressFormData = { label: '', contact_name: '', contact_phone: '', address: '', city: '', area: '', latitude: '', longitude: '', location_consent: false, make_default: false };

function AddressForm({ existing }: { existing?: CustomerAddress }) {
    const form = useForm<AddressFormData>(existing ? { label: existing.label, contact_name: existing.contactName, contact_phone: existing.contactPhone, address: existing.address, city: existing.city, area: existing.area, latitude: existing.latitude.toString(), longitude: existing.longitude.toString(), location_consent: false, make_default: existing.isDefault } : blank);
    const submit = () => existing ? form.put(`/customer/addresses/${existing.publicId}`) : form.post('/customer/addresses', { onSuccess: () => form.reset() });
    return <form className="grid gap-4 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); submit(); }}><FormField label="Label" name={`label-${existing?.publicId ?? 'new'}`} value={form.data.label} error={form.errors.label} onChange={(event) => form.setData('label', event.target.value)} placeholder="Rumah" /><FormField label="Nama penerima" name={`contact-${existing?.publicId ?? 'new'}`} value={form.data.contact_name} error={form.errors.contact_name} onChange={(event) => form.setData('contact_name', event.target.value)} /><FormField label="Nomor telepon" name={`phone-${existing?.publicId ?? 'new'}`} value={form.data.contact_phone} error={form.errors.contact_phone} onChange={(event) => form.setData('contact_phone', event.target.value)} /><FormField label="Kota" name={`city-${existing?.publicId ?? 'new'}`} value={form.data.city} error={form.errors.city} onChange={(event) => form.setData('city', event.target.value)} /><FormField label="Area" name={`area-${existing?.publicId ?? 'new'}`} value={form.data.area} error={form.errors.area} onChange={(event) => form.setData('area', event.target.value)} /><FormField label="Latitude" name={`lat-${existing?.publicId ?? 'new'}`} type="number" step="any" value={form.data.latitude} error={form.errors.latitude} onChange={(event) => form.setData('latitude', event.target.value)} /><FormField label="Longitude" name={`lng-${existing?.publicId ?? 'new'}`} type="number" step="any" value={form.data.longitude} error={form.errors.longitude} onChange={(event) => form.setData('longitude', event.target.value)} /><TextareaField label="Alamat lengkap" name={`address-${existing?.publicId ?? 'new'}`} className="sm:col-span-2" value={form.data.address} error={form.errors.address} onChange={(event) => form.setData('address', event.target.value)} /><label className="flex gap-3 text-sm font-semibold text-copy sm:col-span-2"><input type="checkbox" checked={form.data.location_consent} onChange={(event) => form.setData('location_consent', event.target.checked)} className="mt-0.5 size-5 accent-brand-600" /><span>Saya setuju koordinat ini disimpan untuk validasi radius layanan.{form.errors.location_consent && <span className="block text-xs text-red-700">{form.errors.location_consent}</span>}</span></label><label className="flex items-center gap-3 text-sm font-semibold sm:col-span-2"><input type="checkbox" checked={form.data.make_default} onChange={(event) => form.setData('make_default', event.target.checked)} className="size-5 accent-brand-600" />Jadikan alamat default</label><Button type="submit" disabled={form.processing} className="sm:col-span-2 sm:justify-self-start">{existing ? 'Simpan perubahan' : 'Tambah alamat'}</Button></form>;
}

export default function CustomerAddresses({ addresses }: { addresses: Paginated<CustomerAddress> }) {
    const { flash } = usePage<{ flash?: { status?: string } }>().props;
    return <main className="min-h-screen bg-canvas px-4 py-6 text-ink sm:px-6"><Head title="Alamat saya" /><div className="mx-auto max-w-5xl"><header className="flex flex-wrap items-center justify-between gap-4"><div><Link href="/workspace" className="inline-flex items-center gap-2 text-sm font-bold text-brand-700"><ArrowLeft className="size-4" />Workspace</Link><h1 className="mt-2 text-3xl font-black">Alamat saya</h1><p className="mt-1 text-sm text-muted">Koordinat hanya dipakai untuk memeriksa cakupan outlet.</p></div><Link href="/outlets" className="rounded-xl bg-brand-950 px-4 py-3 text-sm font-bold text-white">Cari outlet</Link></header>{flash?.status && <p className="mt-5 rounded-xl bg-success-soft p-4 text-sm font-bold text-success">{flash.status}</p>}<section className="mt-6 rounded-panel border border-line bg-surface p-6 shadow-panel"><h2 className="text-xl font-black">Tambah alamat</h2><div className="mt-5"><AddressForm /></div></section><section className="mt-6"><h2 className="text-xl font-black">Alamat tersimpan</h2>{addresses.items.length === 0 ? <div className="mt-4"><EmptyState title="Belum ada alamat" description="Tambahkan alamat pickup atau delivery pertama Anda." /></div> : <div className="mt-4 grid gap-4">{addresses.items.map((address) => <details key={address.publicId} className="group rounded-panel border border-line bg-surface p-5 shadow-panel"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-600"><div><h3 className="flex items-center gap-2 font-black"><MapPin className="size-4" />{address.label}{address.isDefault && <span className="rounded-full bg-accent px-2 py-0.5 text-xs text-brand-950">Default</span>}</h3><p className="mt-1 text-sm text-muted">{address.area}, {address.city}</p></div><span className="text-sm font-bold text-brand-700 group-open:hidden">Edit</span></summary><div className="mt-5 border-t border-line pt-5"><AddressForm existing={address} /><div className="mt-4 flex flex-wrap gap-2">{!address.isDefault && <Button variant="secondary" onClick={() => router.post(`/customer/addresses/${address.publicId}/default`)}><Star className="size-4" />Jadikan default</Button>}<Button variant="ghost" onClick={() => { if (window.confirm('Hapus alamat ini?')) router.delete(`/customer/addresses/${address.publicId}`); }}><Trash2 className="size-4" />Hapus</Button></div></div></details>)}</div>}<Pagination meta={addresses.meta} /></section></div></main>;
}
