import { Head, Link } from '@inertiajs/react';
import { ArrowLeft, Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { OrderPageProps } from '@/types/orders';

const money = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 });
const date = new Intl.DateTimeFormat('id-ID', { dateStyle: 'long', timeStyle: 'short', timeZone: 'Asia/Jakarta' });
export default function OrderReceipt({ order, viewer }: OrderPageProps) {
    const base = viewer === 'tenant_owner' ? '/tenant/orders' : '/orders';
    const total = order.grandTotal ?? order.estimatedGrandTotal;
    return <main className="min-h-screen bg-white px-4 py-8 text-ink"><Head title={`Receipt ${order.orderNumber}`} /><div className="mx-auto max-w-2xl"><div className="mb-6 flex justify-between print:hidden"><Link href={`${base}/${order.publicId}`} className="inline-flex items-center gap-2 text-sm font-bold text-brand-700"><ArrowLeft className="size-4" />Detail order</Link><Button onClick={() => window.print()}><Printer className="size-4" />Cetak</Button></div><article className="rounded-panel border border-line p-8 print:border-0"><p className="text-xs font-bold uppercase tracking-widest text-brand-600">Klik Laundry · Receipt skeleton</p><h1 className="mt-3 text-2xl font-black">{order.orderNumber}</h1><p className="mt-1 text-sm text-muted">Dibuat {date.format(new Date(order.createdAt))}</p><div className="mt-8 grid gap-5 sm:grid-cols-2"><div><p className="text-xs text-muted">Tenant / Outlet</p><p className="font-bold">{order.tenantName} / {order.outletName}</p></div><div><p className="text-xs text-muted">Status</p><p className="font-bold">{order.fulfillmentStatus} · {order.paymentStatus}</p></div><div><p className="text-xs text-muted">Paket</p><p className="font-bold">{order.item.packageName}</p></div><div><p className="text-xs text-muted">Pickup</p><p className="font-bold">{date.format(new Date(order.pickupStartsAt))}</p></div></div><dl className="mt-8 space-y-3 border-t border-line pt-6"><div className="flex justify-between"><dt>{order.isEstimate ? 'Estimasi subtotal' : 'Subtotal'}</dt><dd>{money.format(order.itemsSubtotal ?? order.estimatedItemsSubtotal ?? 0)}</dd></div><div className="flex justify-between"><dt>Pickup</dt><dd>{money.format(order.pickupFee)}</dd></div><div className="flex justify-between"><dt>Delivery</dt><dd>{money.format(order.deliveryFee)}</dd></div><div className="flex justify-between border-t border-line pt-3 text-lg font-black"><dt>{order.isEstimate ? 'Estimasi total' : 'Total'}</dt><dd>{total === null ? 'Menunggu berat final' : money.format(total)}</dd></div></dl>{order.isEstimate && <p className="mt-6 text-xs text-muted">Bukan invoice final. Berat dan total final belum dikonfirmasi.</p>}<p className="mt-8 border-t border-line pt-5 text-xs text-muted">Payment provider dan payment URL belum tersedia pada Milestone 4.</p></article></div></main>;
}
